config/routes.rb
QuizSite::Application.routes.draw do

  root 'users#index'

  resources :users, :only => [:show, :create, :new] do
    collection do
      post 'login'
      post 'logout'      
    end
  end

  resource :questions, :only => [:new, :create, :show]

  resource :answers, :only => [:create, :show]

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base

	# has_and_belongs_to_many :users
	has_many :answers
	belongs_to :user

	# 	def self.compare(answer)
	# 	Question.find_by_answer(answer)#match_password(password)
	# end

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :questions
	has_many :answers

	# def self.create_user(user_name, password)
	# 	User.create!(user_name: user_name, password: password)
	# end

	def self.authenticate(password)
		User.find_by_password(password)#match_password(password)
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		answer = Answer.new(params.require(:answer).permit(:value, :question_id, :user_id))
		answer.save!
		question = answer.question

		if (question.answer == answer.value)
			redirect_to answers_path
			flash[:notice] = "Correct!"
		else
			redirect_to answers_path
			flash[:notice] = "Incorrect!"
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def create
		question = Question.create!(question_params)
		# user = question.user
		 # current_user.id
		redirect_to new_questions_path
	end

	def new
		@question = Question.new(:user => current_user)
	end

	def show
		@show_question = Question.order("RANDOM()").first
		@answer = Answer.new(:question => @show_question, :user => current_user)
	end

	private

	  def question_params
	    params.require(:question).permit(:text, :answer, :user_id)
	  end
	
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		User.create!(user_params)
		redirect_to '/'
	end

	def new
		@user = User.new
	end

	def login
	    @user = User.find_by_user_name(params[:user][:user_name])
	    if @user && User.authenticate(params[:user][:password])
	       @name = @user.user_name
	       session[:user_id] = @user.id
	       # render 'users/userprofile'
	       redirect_to user_path(@user)
	    else
	       flash[:error] = "user name or password is invalid"
	    end
	end

	def logout
		session.clear
		redirect_to '/'
	end

private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/show.html.erb
<h1> <%= flash[:notice] %></h1>

app/views/home/index.html.erb
<h2>Signup</h2>

<%= form_for :user, :url => signup_path do |f| %>
	<div>
		<%= f.label :user_name %>
		<%= f.text_field :user_name %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

<h2>Login</h2>

<%= form_for :user, :url => login_path do |f| %>
	<div>
		<% f.label :user_name %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/new.html.erb
<h2>Add a question to the quiz!</h2>

<%= form_for @question do |f| %>

	<%= f.hidden_field :user_id %>
	
	<div>
		<%= f.label :text %>
		<%= f.text_field :text %>
	</div>

	<div>
		<%= f.radio_button :answer, "true" %>
		<%= f.label :answer, "true"  %>
		<%= f.radio_button :answer, "false" %>
		<%= f.label :answer, "false"  %>
	</div>

	<div>
		<%= f.submit "Submit" %>
	</div>

<% end %>

app/views/questions/show.html.erb
<h2>Question</h2><p> <%= @show_question.id %></p>

<p><%= @show_question.text %></p>

<%= form_for @answer do |f| %>
	<%= f.hidden_field :question_id %>
	<%= f.hidden_field :user_id %>
	<div> 
		<%= f.radio_button :value, "true" %>
		<%= f.label "true" %>
		<%= f.radio_button :value, "false" %>
		<%= f.label "false" %>
	</div>

	<div>
		<%= f.submit "Submit" %>
	</div>

<% end %>

app/views/users/index.html.erb
<h2>Welcome to the Quiz!</h2>

<h2>Login</h2>
<%= form_for :user, :url => login_users_path do |f| %>
	<div>
		<%= f.label :user_name %>
		<%= f.text_field :user_name %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.submit "Login" %>
	</div>
<% end %>

<div>
	<a href='/users/new'>Click here to Sign Up!</a>
</div>

app/views/users/new.html.erb
<h2>Signup</h2>

<%= form_for @user do |f| %>
	<div>
		<%= f.label :user_name %>
		<%= f.text_field :user_name %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<h2> WELCOME <%= @name %>!</h2>

<div>
	<a href= '/questions/new' >Click here to add a question!</a>
</div>
<div>
	<a href= '/questions' >Click here to start the quiz!</a>
</div>


<%= form_for :user, :url => logout_users_path do |f| %>
		<%= f.submit "Logout" %>
<% end %>

app/views/users/signup_display.html.erb
<h2>Signup</h2>

<%= form_for :user, :url => signup_path do |f| %>
	<div>
		<%= f.label :user_name %>
		<%= f.text_field :user_name %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

app/views/users/userprofile.html.erb
<h2> WELCOME <%= @name %>!</h2>

<div>
	<a href= '/questions/new' >Click here to add a question!</a>
</div>
<div>
	<a href= '/questions' >Click here to start the quiz!</a>
</div>


<%= form_for :user, :url => logout_path do |f| %>
		<%= f.submit "Logout" %>
<% end %>